before:
  hooks:
    - go mod tidy
builds:
  - dir: ./cmd/rigelctl
    main: .
    binary: rigelctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
archives:
  - format: tar.gz
    # additional archive configuration if needed
